# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: araji-af <araji-af@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/21 12:39:32 by araji-af          #+#    #+#              #
#    Updated: 2024/05/09 20:24:21 by araji-af         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:bullseye

RUN apt-get update -y && apt-get install mariadb-server -y

COPY ./tools/script.sh /

RUN chmod +x script.sh

CMD ["./script.sh"]