# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: araji-af <araji-af@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/22 11:58:22 by araji-af          #+#    #+#              #
#    Updated: 2024/05/09 16:29:52 by araji-af         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:bullseye

RUN apt-get update -y\
    && apt-get install php-fpm php7.4 php-mysql mariadb-client -y curl -y

COPY /tools/initializeWP.sh /


RUN mkdir -p /run/php && chmod +x /initializeWP.sh

CMD ["bash", "./initializeWP.sh"]